// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmtszsqkbqormeevrvvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdHN6c3FrYnFvcm1lZXZydnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTA3MDIsImV4cCI6MjA3Mjk2NjcwMn0.NpihP0rmNKUD3-kyn9McigheA1u5GhtxlCp4CjW1QR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});